spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hirespherex_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: aditya
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    com.hirespherex: DEBUG
jwt:
  secret: dGhpc19pc19hX3Rlc3Rfc2VjcmV0X3BsZWFzZV9yZXBsYWNlX3Byb2Q=
